[project]
name = "hfagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "huggingface-hub>=1.2.2",
    "pydantic>=2.12.5",
]

[tool.uv.workspace]
members = [
    "hfagent",
]
